import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./head/Nav";
import Foter from "./head/Footer";
import { ToastContainer } from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';

import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
    <div className="  mx-10">
 
        {children}
        
        
    </div>
    <Foter/>
        <ToastContainer/>
        </body>
    </html>
  );
}
